#KubeJS Client Properties
<<<<<<< HEAD
#Mon Feb 23 00:32:32 CST 2026
backgroundColor=2E3440
barBorderColor=ECEFF4
barColor=ECEFF4
blurScaledPackIcon=true
disableRecipeBook=false
exportAtlases=false
fmlLogColor=ECEFF4
fmlMemoryColor=ECEFF4
menuBackgroundBrightness=64
menuBackgroundScale=32.0
menuInnerBackgroundBrightness=32
overrideColors=false
showTagNames=false
title=
=======
#Tue Aug 31 15:51:05 CEST 2021
fmlLogColor=B8B2A6
barBorderColor=F4F3F3
overrideColors=true
menuBackgroundScale=32.0
fmlMemoryColor=F4F3F3
barColor=5EAAA8
showTagNames=true
menuBackgroundBrightness=64
disableRecipeBook=false
menuInnerBackgroundBrightness=32
title=Create: Above and Beyond
backgroundColor=B8B2A6
exportAtlases=false
>>>>>>> b3684595b8499d393feebf065b07383882b7f802
