#KubeJS Common Properties
<<<<<<< HEAD
#Mon Feb 23 00:32:34 CST 2026
allowAsyncStreams=true
announceReload=true
creativeModeTabIcon=minecraft\:purple_dye
hideServerScriptErrors=false
ignoreCustomUniqueRecipeIds=false
matchJsonRecipes=true
packmode=
saveDevPropertiesInConfig=false
serverOnly=false
startupErrorGUI=true
startupErrorReportUrl=
=======
#Mon Oct 04 13:29:27 CEST 2021
hideServerScriptErrors=false
packmode=default
invertClassLoader=true
debugInfo=false
announceReload=true
serverOnly=false
>>>>>>> b3684595b8499d393feebf065b07383882b7f802
