State:6
Info:正式版 1.16.5, Forge 36.2.20
Logo:pack://application:,,,/Plain Craft Launcher 2;component/Images/Blocks/Anvil.png
ReleaseTime:2021-01-15 00:05
VersionFabric:
VersionOptiFine:
VersionLiteLoader:False
VersionForge:36.2.20
VersionNeoForge:
VersionVanillaName:1.16.5
VersionVanilla:16.0.5
VersionArgumentIndieV2:True
VersionRamType:0
VersionServerEnter:addre.dpdns.org
VersionAdvanceDisableModUpdate:True
VersionAdvanceJava:False
VersionAdvanceAssetsV2:True
VersionAdvanceDisableJLW:True
IsStar:False
VersionArgumentIndie:1
